# This workflow will upload a Python Package when a release is created

name: Build and publish library

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies
        run: |
          poetry install
      - name: package library
        run: poetry build
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$PYPI_TOKEN"
          poetry publish
